server:
  port: 8085
  servlet:
    context-path: ''

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.201.71.223:3406/qishanor_nav?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC&allowPublicKeyRetrieval=true
    username: qishanor_nav
    password: 12345678
  freemarker:
    charset: utf-8
    suffix: .ftl


mybatis-plus:
  configuration:
    # 设置日志实现为标准输出，可输出 SQL 信息到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## Sa-Token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: nav
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true