spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.201.71.223:3406/qishanor_nav_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC&allowPublicKeyRetrieval=true
    username: qishanor_nav_dev
    password: 12345678
  freemarker:
    charset: utf-8
    suffix: .ftl