server:
  port: 8085
  servlet:
    context-path: ''

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://154.201.71.223:3406/qishanor_nav?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC&allowPublicKeyRetrieval=true
    username: qishanor_nav
    password: 12345678
  freemarker:
    charset: utf-8
    suffix: .ftl